{% set version = '3.1.4' %}
{% set mpi = mpi or 'mpich' %}  # [not win] 
{% set mpi = mpi or 'msmpi' %}  # [win] 

package:
  name: mpi4py
  version: {{ version }}

source:
  fn: mpi4py-{{ version }}.tar.gz
  url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
  sha256: 17858f2ebc623220d0120d1fa8d428d033dde749c4bc35b33d81a66ad7f93480

build:
  number: 0
  script: 
    - {{ PYTHON }} conf/cythonize.py
    - {{ PYTHON }} -m pip install --no-deps . -vv
  # s390x is missing a mpi variant (no openmpi or mpich)
  skip: True  # [py<37 or s390x]

requirements:
  build:
    - {{ compiler('c') }}  # [not (linux and x86_64)]
    - gcc_linux-64 7.5     # [linux and x86_64]
  host:
    - python
    - pip
    - cython
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test: {}

about:
  home: https://github.com/mpi4py/mpi4py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.io/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
