{% set version = '3.1.4' %}

{% if win %}
  # msmpi is the only MPI variant for Windows
  {% set mpi ='msmpi' %}
{% else %}
  {% set mpi = mpi or 'mpich' %}
{% endif %}

package:
  name: mpi4py
  version: {{ version }}

source:
  url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
  sha256: 17858f2ebc623220d0120d1fa8d428d033dde749c4bc35b33d81a66ad7f93480

build:
  number: 1
  script: 
    - {{ PYTHON }} conf/cythonize.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - wheel
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test:
  requires:
    - pip

about:
  home: https://github.com/mpi4py/mpi4py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.io/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
  skip-lints:
    - missing_doc_source_url
    - missing_license_url
